### PR TITLE
fixes Issue 45 - cant generate using ent and then run

### PR DESCRIPTION
**Pull request by gedw99**
https://github.com/mikestefanello/pagoda/issues/45

Al I did was run go-mod-upgrade and go mod tidy
https://github.com/oligot/go-mod-upgrade

This does a sweep through everything. I updated to all latest dependencies, and did a generate and run and test.

This is my first PR, so if I missed something or should have done it on a branch, let me know.

### CODE REVIEW

**Comment by gedw99** [comment]
https://github.com/mikestefanello/pagoda/blob/main/pkg/context/context_test.go#L21 is the source of a test failure on my laptop. It's minor I think. Not sure if it was there before

**Comment by gedw99** [comment]
@mikestefanello do you require that PRs be signed ?

**Comment by mikestefanello** [comment]
Thanks for taking care of this. I'll fix the context_test issue now.

**Review by mikestefanello — APPROVED** [review]

**Comment by gedw99** [comment]
> Thanks for taking care of this. I'll fix the context_test issue now.

thanks @mikestefanello

**Pull request merged**
